### ISSUE TITLE
11X11 grid

### ISSUE THREAD

**Issue by Andlibmehndi** [mpatacchiola/dissecting-reinforcement-learning#13]
Hi @mpatacchiola  i have 11X11 grid so how can i make transition_matrix 
can you please help me?
Is there any generic code for creating transition_matrix by giving row and col of grid?

**Comment by mpatacchiola** [comment]
Hi @Andlibmehndi 

Yes you can define your gridworld with a specific number of rows and columns:

```python
from gridworld import GridWorld
env = GridWorld(tot_row=11, tot_col=11)
```

You can set the reward, transition, and state matrices using the methods of the class.
Give a look [to the code](https://github.com/mpatacchiola/dissecting-reinforcement-learning/blob/master/environments/gridworld.py) for more details about each method:

**Comment by mpatacchiola** [comment]
Closed for inactivity
