### ISSUE TITLE
Problem in executing: "Montecarlo_control.py"

### ISSUE THREAD

**Issue by lucanicolienel** [mpatacchiola/dissecting-reinforcement-learning#7]
Dear Massimiliano, 

I am trying to execute your code "Montecarlo_control.py" from post number 2.

I have got the following issue:
![image](https://user-images.githubusercontent.com/43605453/47922690-f3796200-deb7-11e8-9da1-c9b5e9416ec5.png)

it seems that` if(checkup_matrix[row, col] == 0):` receives a row index that is a float and not a int value.
In this way it is not able to search index of the table.

Luca

**Comment by mpatacchiola** [comment]
Hi @lucanicolienel 

I fixed the bug, it was necessary to cast to int the variables in line 157 and 158. You can download the updated file from the repository.

Cheers
